# Generated by Django 2.0.10 on 2019-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='network_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.IntegerField()),
                ('description', models.CharField(max_length=64)),
                ('customer_id', models.DecimalField(decimal_places=3, max_digits=50)),
                ('ip_public', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'ipaddresses',
            },
        ),
    ]
