# Generated by Django 2.0.10 on 2019-03-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_base',
            name='sid',
            field=models.DecimalField(decimal_places=3, max_digits=25),
        ),
    ]
