# Generated by Django 2.0.5 on 2019-04-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dir_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=64)),
                ('customer_id', models.CharField(max_length=50)),
                ('ip_public', models.CharField(max_length=20, null=True)),
                ('date_t', models.DateField(auto_now_add=True)),
                ('time_t', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
