# Generated by Django 2.0.10 on 2019-03-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20190305_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain_base',
            options={'managed': False},
        ),
    ]
