# Generated by Django 2.0.10 on 2019-03-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0003_auto_20190306_1748'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complain_base',
            table='ipaddresses',
        ),
    ]
